language: java
sudo: false
env:
  global:
    - CODECOV_TOKEN="88041e0f-52ec-4082-8ac6-87b5c6c66338"
script: mvn "clean install cobertura:cobertura"
after_success:
  - bash <(curl -s https://codecov.io/bash)