language: java
sudo: false

env:
  global:
    - CODECOV_TOKEN="88041e0f-52ec-4082-8ac6-87b5c6c66338"
dist: xenial
jdk:
  - openjdk8
install: true
before_install:
  - chmod a+x ./mvnw
script: ./mvnw clean install cobertura:cobertura -DskipTests
after_success:
  - bash <(curl -s https://codecov.io/bash) -t 88041e0f-52ec-4082-8ac6-87b5c6c66338