version: 2 
jobs: 
  build: 
    
    working_directory: ~/kafka-embedded

    docker: 
      - image: openjdk:11.0.5-jdk

    steps: 

      - checkout: 

      - restore_cache: 
          
          key: kafka-embedded-{{ checksum "pom.xml" }}
      
      - run: ./mvnw clean install jacoco:prepare-agent jacoco:report
      
      - store_test_results: 
      
          path: target/surefire-reports
      
      